/**
* Generated by LEA for Arma 3
* Version: 2.0.15
* Tue Feb 25 18:32:56 CET 2014
* 
* Call the script: _dummy = this execvm "caja_medica_XMed.sqf";
* 
*/

while {true} do {
 if isnull _this exitwith {};
 if not alive _this exitwith {};
 clearweaponcargo _this;
 clearmagazinecargo _this;
 clearitemcargo _this;
 clearBackpackCargo _this;

 _this additemcargo ["x39_medikit",200];
 _this additemcargo ["x39_bandage",200];
 _this additemcargo ["x39_morphine",200];
 _this additemcargo ["x39_defibrillator",200];
 _this additemcargo ["x39_bloodbag",200];
 _this additemcargo ["x39_epinephrine",200];
 _this additemcargo ["x39_tourniquet",200];

 sleep 300;
};
